<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38046" started-at="2019-03-05T00:11:24Z" finished-at="2019-03-05T00:12:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38046" started-at="2019-03-05T00:11:24Z" finished-at="2019-03-05T00:12:02Z">
      <class name="Academy.E2EProject.ValidateTitle">
        <test-method status="PASS" signature="initialize()[pri:0, instance:Academy.E2EProject.ValidateTitle@4f83df68]" name="initialize" is-config="true" duration-ms="35705" started-at="2019-03-05T00:11:24Z" finished-at="2019-03-05T00:12:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="featuredcourses()[pri:0, instance:Academy.E2EProject.ValidateTitle@4f83df68]" name="featuredcourses" duration-ms="120" started-at="2019-03-05T00:12:00Z" finished-at="2019-03-05T00:12:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [FEATURED COUR44SES] but found [FEATURED COURSES]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [FEATURED COUR44SES] but found [FEATURED COURSES]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Academy.E2EProject.ValidateTitle.featuredcourses(ValidateTitle.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- featuredcourses -->
        <test-method status="PASS" signature="close()[pri:0, instance:Academy.E2EProject.ValidateTitle@4f83df68]" name="close" is-config="true" duration-ms="2159" started-at="2019-03-05T00:12:00Z" finished-at="2019-03-05T00:12:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Academy.E2EProject.ValidateTitle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
